/*
 * This file is generated by jOOQ.
 */
package com.experts.core.biller.statemachine.api.jooq.tables.records;


import com.experts.core.biller.statemachine.api.jooq.tables.Users_;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users_Record extends UpdatableRecordImpl<Users_Record> implements Record10<Long, Timestamp, Timestamp, String, Boolean, Boolean, String, String, String, String> {

    private static final long serialVersionUID = 1596754345;

    /**
     * Setter for <code>public.users_.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.users_.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.users_.createddate</code>.
     */
    public void setCreateddate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.users_.createddate</code>.
     */
    public Timestamp getCreateddate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>public.users_.modifieddate</code>.
     */
    public void setModifieddate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.users_.modifieddate</code>.
     */
    public Timestamp getModifieddate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.users_.username</code>.
     */
    public void setUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.users_.username</code>.
     */
    public String getUsername() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.users_.blocked</code>.
     */
    public void setBlocked(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.users_.blocked</code>.
     */
    public Boolean getBlocked() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.users_.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.users_.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.users_.password</code>.
     */
    public void setPassword(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.users_.password</code>.
     */
    public String getPassword() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.users_.lastmodifiedby</code>.
     */
    public void setLastmodifiedby(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.users_.lastmodifiedby</code>.
     */
    public String getLastmodifiedby() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.users_.password_token</code>.
     */
    public void setPasswordToken(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.users_.password_token</code>.
     */
    public String getPasswordToken() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.users_.username_token</code>.
     */
    public void setUsernameToken(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.users_.username_token</code>.
     */
    public String getUsernameToken() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Timestamp, Timestamp, String, Boolean, Boolean, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Timestamp, Timestamp, String, Boolean, Boolean, String, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Users_.USERS_.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Users_.USERS_.CREATEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Users_.USERS_.MODIFIEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Users_.USERS_.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return Users_.USERS_.BLOCKED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return Users_.USERS_.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Users_.USERS_.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Users_.USERS_.LASTMODIFIEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Users_.USERS_.PASSWORD_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Users_.USERS_.USERNAME_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getModifieddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getBlocked();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getLastmodifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getPasswordToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getUsernameToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getModifieddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getBlocked();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getLastmodifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getPasswordToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getUsernameToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Users_Record value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Users_Record value2(Timestamp value) {
        setCreateddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Users_Record value3(Timestamp value) {
        setModifieddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Users_Record value4(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Users_Record value5(Boolean value) {
        setBlocked(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Users_Record value6(Boolean value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Users_Record value7(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Users_Record value8(String value) {
        setLastmodifiedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Users_Record value9(String value) {
        setPasswordToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Users_Record value10(String value) {
        setUsernameToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Users_Record values(Long value1, Timestamp value2, Timestamp value3, String value4, Boolean value5, Boolean value6, String value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Users_Record
     */
    public Users_Record() {
        super(Users_.USERS_);
    }

    /**
     * Create a detached, initialised Users_Record
     */
    public Users_Record(Long id, Timestamp createddate, Timestamp modifieddate, String username, Boolean blocked, Boolean enabled, String password, String lastmodifiedby, String passwordToken, String usernameToken) {
        super(Users_.USERS_);

        set(0, id);
        set(1, createddate);
        set(2, modifieddate);
        set(3, username);
        set(4, blocked);
        set(5, enabled);
        set(6, password);
        set(7, lastmodifiedby);
        set(8, passwordToken);
        set(9, usernameToken);
    }
}
