/*
 * This file is generated by jOOQ.
 */
package com.experts.core.biller.statemachine.api.jooq;


import com.experts.core.biller.statemachine.api.jooq.tables.Authorities;
import com.experts.core.biller.statemachine.api.jooq.tables.Authorities__;
import com.experts.core.biller.statemachine.api.jooq.tables.BillCreationHistory;
import com.experts.core.biller.statemachine.api.jooq.tables.BillPullRequest;
import com.experts.core.biller.statemachine.api.jooq.tables.Billingcreation;
import com.experts.core.biller.statemachine.api.jooq.tables.CompletedState;
import com.experts.core.biller.statemachine.api.jooq.tables.Customer;
import com.experts.core.biller.statemachine.api.jooq.tables.Customtrackingrevisionentity;
import com.experts.core.biller.statemachine.api.jooq.tables.InitialState;
import com.experts.core.biller.statemachine.api.jooq.tables.InquiryBillCurrent;
import com.experts.core.biller.statemachine.api.jooq.tables.InquiryHistory;
import com.experts.core.biller.statemachine.api.jooq.tables.ModifiedEntity;
import com.experts.core.biller.statemachine.api.jooq.tables.PayState;
import com.experts.core.biller.statemachine.api.jooq.tables.Payment;
import com.experts.core.biller.statemachine.api.jooq.tables.PaymentStatus;
import com.experts.core.biller.statemachine.api.jooq.tables.Person;
import com.experts.core.biller.statemachine.api.jooq.tables.ProcessState;
import com.experts.core.biller.statemachine.api.jooq.tables.RolesAuth;
import com.experts.core.biller.statemachine.api.jooq.tables.Tasks;
import com.experts.core.biller.statemachine.api.jooq.tables.TasksVarible;
import com.experts.core.biller.statemachine.api.jooq.tables.Transaction;
import com.experts.core.biller.statemachine.api.jooq.tables.Transactionstatus;
import com.experts.core.biller.statemachine.api.jooq.tables.TxAccount;
import com.experts.core.biller.statemachine.api.jooq.tables.TxKullaniciRol;
import com.experts.core.biller.statemachine.api.jooq.tables.TxMenu;
import com.experts.core.biller.statemachine.api.jooq.tables.TxPage;
import com.experts.core.biller.statemachine.api.jooq.tables.TxRol;
import com.experts.core.biller.statemachine.api.jooq.tables.TxRolYetki;
import com.experts.core.biller.statemachine.api.jooq.tables.TxUser;
import com.experts.core.biller.statemachine.api.jooq.tables.TxYetki;
import com.experts.core.biller.statemachine.api.jooq.tables.UserAuthorities;
import com.experts.core.biller.statemachine.api.jooq.tables.Users;
import com.experts.core.biller.statemachine.api.jooq.tables.Users_;
import com.experts.core.biller.statemachine.api.jooq.tables.Users__;
import com.experts.core.biller.statemachine.api.jooq.tables.WaitingState;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -373647522;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.authorities</code>.
     */
    public final Authorities AUTHORITIES = com.experts.core.biller.statemachine.api.jooq.tables.Authorities.AUTHORITIES;

    /**
     * The table <code>public.authorities__</code>.
     */
    public final Authorities__ AUTHORITIES__ = com.experts.core.biller.statemachine.api.jooq.tables.Authorities__.AUTHORITIES__;

    /**
     * The table <code>public.bill_creation_history</code>.
     */
    public final BillCreationHistory BILL_CREATION_HISTORY = com.experts.core.biller.statemachine.api.jooq.tables.BillCreationHistory.BILL_CREATION_HISTORY;

    /**
     * The table <code>public.bill_pull_request</code>.
     */
    public final BillPullRequest BILL_PULL_REQUEST = com.experts.core.biller.statemachine.api.jooq.tables.BillPullRequest.BILL_PULL_REQUEST;

    /**
     * The table <code>public.billingcreation</code>.
     */
    public final Billingcreation BILLINGCREATION = com.experts.core.biller.statemachine.api.jooq.tables.Billingcreation.BILLINGCREATION;

    /**
     * The table <code>public.completed_state</code>.
     */
    public final CompletedState COMPLETED_STATE = com.experts.core.biller.statemachine.api.jooq.tables.CompletedState.COMPLETED_STATE;

    /**
     * The table <code>public.customer</code>.
     */
    public final Customer CUSTOMER = com.experts.core.biller.statemachine.api.jooq.tables.Customer.CUSTOMER;

    /**
     * The table <code>public.customtrackingrevisionentity</code>.
     */
    public final Customtrackingrevisionentity CUSTOMTRACKINGREVISIONENTITY = com.experts.core.biller.statemachine.api.jooq.tables.Customtrackingrevisionentity.CUSTOMTRACKINGREVISIONENTITY;

    /**
     * The table <code>public.initial_state</code>.
     */
    public final InitialState INITIAL_STATE = com.experts.core.biller.statemachine.api.jooq.tables.InitialState.INITIAL_STATE;

    /**
     * The table <code>public.inquiry_bill_current</code>.
     */
    public final InquiryBillCurrent INQUIRY_BILL_CURRENT = com.experts.core.biller.statemachine.api.jooq.tables.InquiryBillCurrent.INQUIRY_BILL_CURRENT;

    /**
     * The table <code>public.inquiry_history</code>.
     */
    public final InquiryHistory INQUIRY_HISTORY = com.experts.core.biller.statemachine.api.jooq.tables.InquiryHistory.INQUIRY_HISTORY;

    /**
     * The table <code>public.modified_entity</code>.
     */
    public final ModifiedEntity MODIFIED_ENTITY = com.experts.core.biller.statemachine.api.jooq.tables.ModifiedEntity.MODIFIED_ENTITY;

    /**
     * The table <code>public.pay_state</code>.
     */
    public final PayState PAY_STATE = com.experts.core.biller.statemachine.api.jooq.tables.PayState.PAY_STATE;

    /**
     * The table <code>public.payment</code>.
     */
    public final Payment PAYMENT = com.experts.core.biller.statemachine.api.jooq.tables.Payment.PAYMENT;

    /**
     * The table <code>public.payment_status</code>.
     */
    public final PaymentStatus PAYMENT_STATUS = com.experts.core.biller.statemachine.api.jooq.tables.PaymentStatus.PAYMENT_STATUS;

    /**
     * The table <code>public.person</code>.
     */
    public final Person PERSON = com.experts.core.biller.statemachine.api.jooq.tables.Person.PERSON;

    /**
     * The table <code>public.process_state</code>.
     */
    public final ProcessState PROCESS_STATE = com.experts.core.biller.statemachine.api.jooq.tables.ProcessState.PROCESS_STATE;

    /**
     * The table <code>public.roles_auth</code>.
     */
    public final RolesAuth ROLES_AUTH = com.experts.core.biller.statemachine.api.jooq.tables.RolesAuth.ROLES_AUTH;

    /**
     * The table <code>public.tasks</code>.
     */
    public final Tasks TASKS = com.experts.core.biller.statemachine.api.jooq.tables.Tasks.TASKS;

    /**
     * The table <code>public.tasks_varible</code>.
     */
    public final TasksVarible TASKS_VARIBLE = com.experts.core.biller.statemachine.api.jooq.tables.TasksVarible.TASKS_VARIBLE;

    /**
     * The table <code>public.transaction</code>.
     */
    public final Transaction TRANSACTION = com.experts.core.biller.statemachine.api.jooq.tables.Transaction.TRANSACTION;

    /**
     * The table <code>public.transactionstatus</code>.
     */
    public final Transactionstatus TRANSACTIONSTATUS = com.experts.core.biller.statemachine.api.jooq.tables.Transactionstatus.TRANSACTIONSTATUS;

    /**
     * The table <code>public.tx_account</code>.
     */
    public final TxAccount TX_ACCOUNT = com.experts.core.biller.statemachine.api.jooq.tables.TxAccount.TX_ACCOUNT;

    /**
     * The table <code>public.tx_kullanici_rol</code>.
     */
    public final TxKullaniciRol TX_KULLANICI_ROL = com.experts.core.biller.statemachine.api.jooq.tables.TxKullaniciRol.TX_KULLANICI_ROL;

    /**
     * The table <code>public.tx_menu</code>.
     */
    public final TxMenu TX_MENU = com.experts.core.biller.statemachine.api.jooq.tables.TxMenu.TX_MENU;

    /**
     * The table <code>public.tx_page</code>.
     */
    public final TxPage TX_PAGE = com.experts.core.biller.statemachine.api.jooq.tables.TxPage.TX_PAGE;

    /**
     * The table <code>public.tx_rol</code>.
     */
    public final TxRol TX_ROL = com.experts.core.biller.statemachine.api.jooq.tables.TxRol.TX_ROL;

    /**
     * The table <code>public.tx_rol_yetki</code>.
     */
    public final TxRolYetki TX_ROL_YETKI = com.experts.core.biller.statemachine.api.jooq.tables.TxRolYetki.TX_ROL_YETKI;

    /**
     * The table <code>public.tx_user</code>.
     */
    public final TxUser TX_USER = com.experts.core.biller.statemachine.api.jooq.tables.TxUser.TX_USER;

    /**
     * The table <code>public.tx_yetki</code>.
     */
    public final TxYetki TX_YETKI = com.experts.core.biller.statemachine.api.jooq.tables.TxYetki.TX_YETKI;

    /**
     * The table <code>public.user_authorities</code>.
     */
    public final UserAuthorities USER_AUTHORITIES = com.experts.core.biller.statemachine.api.jooq.tables.UserAuthorities.USER_AUTHORITIES;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = com.experts.core.biller.statemachine.api.jooq.tables.Users.USERS;

    /**
     * The table <code>public.users_</code>.
     */
    public final Users_ USERS_ = com.experts.core.biller.statemachine.api.jooq.tables.Users_.USERS_;

    /**
     * The table <code>public.users__</code>.
     */
    public final Users__ USERS__ = com.experts.core.biller.statemachine.api.jooq.tables.Users__.USERS__;

    /**
     * The table <code>public.waiting_state</code>.
     */
    public final WaitingState WAITING_STATE = com.experts.core.biller.statemachine.api.jooq.tables.WaitingState.WAITING_STATE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.AUTHORITIES___ID_SEQ,
            Sequences.AUTHORITIES_ID_SEQ,
            Sequences.HIBERNATE_SEQUENCE,
            Sequences.SQ_SOLICITACAO,
            Sequences.USERS___ID_SEQ,
            Sequences.USERS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Authorities.AUTHORITIES,
            Authorities__.AUTHORITIES__,
            BillCreationHistory.BILL_CREATION_HISTORY,
            BillPullRequest.BILL_PULL_REQUEST,
            Billingcreation.BILLINGCREATION,
            CompletedState.COMPLETED_STATE,
            Customer.CUSTOMER,
            Customtrackingrevisionentity.CUSTOMTRACKINGREVISIONENTITY,
            InitialState.INITIAL_STATE,
            InquiryBillCurrent.INQUIRY_BILL_CURRENT,
            InquiryHistory.INQUIRY_HISTORY,
            ModifiedEntity.MODIFIED_ENTITY,
            PayState.PAY_STATE,
            Payment.PAYMENT,
            PaymentStatus.PAYMENT_STATUS,
            Person.PERSON,
            ProcessState.PROCESS_STATE,
            RolesAuth.ROLES_AUTH,
            Tasks.TASKS,
            TasksVarible.TASKS_VARIBLE,
            Transaction.TRANSACTION,
            Transactionstatus.TRANSACTIONSTATUS,
            TxAccount.TX_ACCOUNT,
            TxKullaniciRol.TX_KULLANICI_ROL,
            TxMenu.TX_MENU,
            TxPage.TX_PAGE,
            TxRol.TX_ROL,
            TxRolYetki.TX_ROL_YETKI,
            TxUser.TX_USER,
            TxYetki.TX_YETKI,
            UserAuthorities.USER_AUTHORITIES,
            Users.USERS,
            Users_.USERS_,
            Users__.USERS__,
            WaitingState.WAITING_STATE);
    }
}
