/*
 * This file is generated by jOOQ.
 */
package com.experts.core.biller.statemachine.api.jooq.tables;


import com.experts.core.biller.statemachine.api.jooq.Indexes;
import com.experts.core.biller.statemachine.api.jooq.Keys;
import com.experts.core.biller.statemachine.api.jooq.Public;
import com.experts.core.biller.statemachine.api.jooq.tables.records.CustomtrackingrevisionentityRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customtrackingrevisionentity extends TableImpl<CustomtrackingrevisionentityRecord> {

    private static final long serialVersionUID = 164011686;

    /**
     * The reference instance of <code>public.customtrackingrevisionentity</code>
     */
    public static final Customtrackingrevisionentity CUSTOMTRACKINGREVISIONENTITY = new Customtrackingrevisionentity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomtrackingrevisionentityRecord> getRecordType() {
        return CustomtrackingrevisionentityRecord.class;
    }

    /**
     * The column <code>public.customtrackingrevisionentity.customid</code>.
     */
    public final TableField<CustomtrackingrevisionentityRecord, Integer> CUSTOMID = createField("customid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.customtrackingrevisionentity.customtimestamp</code>.
     */
    public final TableField<CustomtrackingrevisionentityRecord, Long> CUSTOMTIMESTAMP = createField("customtimestamp", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.customtrackingrevisionentity.username</code>.
     */
    public final TableField<CustomtrackingrevisionentityRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>public.customtrackingrevisionentity</code> table reference
     */
    public Customtrackingrevisionentity() {
        this(DSL.name("customtrackingrevisionentity"), null);
    }

    /**
     * Create an aliased <code>public.customtrackingrevisionentity</code> table reference
     */
    public Customtrackingrevisionentity(String alias) {
        this(DSL.name(alias), CUSTOMTRACKINGREVISIONENTITY);
    }

    /**
     * Create an aliased <code>public.customtrackingrevisionentity</code> table reference
     */
    public Customtrackingrevisionentity(Name alias) {
        this(alias, CUSTOMTRACKINGREVISIONENTITY);
    }

    private Customtrackingrevisionentity(Name alias, Table<CustomtrackingrevisionentityRecord> aliased) {
        this(alias, aliased, null);
    }

    private Customtrackingrevisionentity(Name alias, Table<CustomtrackingrevisionentityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Customtrackingrevisionentity(Table<O> child, ForeignKey<O, CustomtrackingrevisionentityRecord> key) {
        super(child, key, CUSTOMTRACKINGREVISIONENTITY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CUSTOMTRACKINGREVISIONENTITY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CustomtrackingrevisionentityRecord> getPrimaryKey() {
        return Keys.CUSTOMTRACKINGREVISIONENTITY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CustomtrackingrevisionentityRecord>> getKeys() {
        return Arrays.<UniqueKey<CustomtrackingrevisionentityRecord>>asList(Keys.CUSTOMTRACKINGREVISIONENTITY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Customtrackingrevisionentity as(String alias) {
        return new Customtrackingrevisionentity(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Customtrackingrevisionentity as(Name alias) {
        return new Customtrackingrevisionentity(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Customtrackingrevisionentity rename(String name) {
        return new Customtrackingrevisionentity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Customtrackingrevisionentity rename(Name name) {
        return new Customtrackingrevisionentity(name, null);
    }
}
